server:
  port: 9701

spring:
  profiles:
    active: dev
  application:
    name: integration-app
  datasource:
    url: jdbc:mysql://192.168.95.70:3306/integration?useUnicode=true&characterEncoding=utf8
    username: root
    password: beyondsoft
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
